# sonar-project.properties
sonar.projectKey=phalberg_configlock
sonar.organization=phalberg

sonar.sources=src/cfglock
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8