# sonar-project.properties
sonar.organization=YOUR_SONAR_ORG_KEY
sonar.projectKey=YOUR_PROJECT_KEY

sonar.sources=src/configlock
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8