# sonar-project.properties
sonar.organization=phalberg_configlock
sonar.projectKey=phalberg

sonar.sources=src/configlock
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8