name: CI

on: [push, pull_request]

permissions:
  contents: read



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.11.14"
      - run: uv lock --locked
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install configlock for uv
        run: pip install -e .

      - name: tests
        run: uv run pytest

      - name: Show configlock CLI help with `uv`
        run: configlock --help

      - name: initialize the file first using configlock
        run: configlock init project_info.yaml
      - name: check locked file
        run: configlock lock project_info.yaml
