name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.11.14"

      - run: uv lock --locked

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install configlock for uv
        run: pip install -e .

      - name: tests
        run: uv run pytest

      - name: Show configlock CLI help with `uv`
        run: configlock --help

      - name: initialize the file first using configlock
        run: configlock init project_info.yaml

      - name: check locked file
        run: configlock lock project_info.yaml

      - name: linting
        run: uvx ruff check .

      - name: formatting
        run: uvx ruff format --check .

      - name: type_consitency
        run: uv run pyright .

      - name: complexity check
        run: uvx radon cc -s -a .

      - name: tests with coverage
        run: |
          uv run pytest -v --durations=0 --cov=configlock --cov-report=term-missing --cov-report=xml:coverage.xml
          ls -lah coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

      - name: SonarQube Cloud scan
        uses: SonarSource/sonarqube-scan-action@v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: build
        run: uv build